# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run.
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [windows,linux, darwin]
        goarch: [amd64]
      fail-fast: false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
      BIN_NAME: ${{ github.event.repository.name }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: make go env
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - name: Build Binary
        run: |
          go build -trimpath -o artifact/${BIN_NAME}_${GOOS}_${GOARCH} .
      - name: Windows Rename
        if: matrix.goos == 'windows'
        run: |
          cd ./artifact || exit 1
          mv ${BIN_NAME}_${GOOS}_${GOARCH}{,.exe}

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./artifact/*
          tag: ${{ github.ref }}
